-- O cliente é um perfil distinto de funcionário; vincula o cadastro existente ao Auth.
alter table public.cliente add column if not exists auth_user_id uuid
  unique references auth.users(id) on delete set null;
grant select (auth_user_id) on public.cliente to service_role;
grant insert (auth_user_id) on public.cliente to service_role;
grant update (auth_user_id) on public.cliente to service_role;

create or replace function public.admin_register_client(p_payload jsonb)
returns integer language plpgsql security invoker set search_path = '' as $$
declare
  v_email text := lower(btrim(p_payload->>'email'));
  v_cpf text := p_payload->>'cpf';
  v_id_cpf integer;
  v_id_email integer;
  v_id integer;
  v_auth uuid := nullif(p_payload->>'authUserId','')::uuid;
begin
  if v_auth is null or length(v_cpf) <> 11 or length(v_email) < 5
    then raise exception 'Dados obrigatórios do cliente ausentes'; end if;
  select id_cliente into v_id_cpf from public.cliente where cpf = v_cpf and excluido_em is null limit 1;
  select id_cliente into v_id_email from public.cliente where lower(email) = v_email and excluido_em is null limit 1;
  if v_id_cpf is not null and v_id_email is not null and v_id_cpf <> v_id_email
    then raise exception 'CPF e e-mail pertencem a clientes diferentes'; end if;
  v_id := coalesce(v_id_cpf,v_id_email);
  if v_id is not null then
    update public.cliente set auth_user_id = v_auth
      where id_cliente = v_id and auth_user_id is null;
    if not found then raise exception 'Este cliente já tem uma conta vinculada'; end if;
  else
    insert into public.cliente (nome,email,telefone,cpf,auth_user_id)
      values (btrim(p_payload->>'name'),v_email,btrim(p_payload->>'phone'),v_cpf,v_auth)
      returning id_cliente into v_id;
  end if;
  return v_id;
end $$;
revoke all on function public.admin_register_client(jsonb) from public,anon,authenticated;
grant execute on function public.admin_register_client(jsonb) to service_role;

create or replace function public.admin_register_employee(p_payload jsonb)
returns integer language plpgsql security invoker set search_path = '' as $$
declare v_id integer; v_role text;
begin
  v_role := p_payload->>'profile';
  if v_role not in ('Administrador','Mecânico') or p_payload->>'position' <> v_role
    then raise exception 'Cargo e perfil incompatíveis'; end if;
  if nullif(p_payload->>'authUserId','') is null then raise exception 'Conta Auth ausente'; end if;
  insert into public.funcionario(nome,email,telefone,cpf,cargo,perfil_acesso,auth_user_id)
    values(btrim(p_payload->>'name'),lower(btrim(p_payload->>'email')),
      btrim(p_payload->>'phone'),p_payload->>'cpf',v_role,v_role,
      (p_payload->>'authUserId')::uuid)
    returning id_funcionario into v_id;
  if v_role = 'Mecânico' then insert into public.mecanico(id_funcionario) values(v_id); end if;
  return v_id;
end $$;

-- O painel recebe eventos relevantes, sem depender de uma sessão web aberta.
create table public.admin_notifications (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('new_order','waiting_part','ready','cancelled')),
  order_id integer references public.ordem_servico(id_os) on delete cascade,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);
create index admin_notifications_recent_idx on public.admin_notifications (created_at desc,id desc);
create table public.admin_notification_receipts (
  notification_id bigint not null references public.admin_notifications(id) on delete cascade,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz,
  dismissed_at timestamptz,
  primary key (notification_id,admin_user_id)
);
create index admin_notification_receipts_admin_idx on public.admin_notification_receipts (admin_user_id,dismissed_at);
alter table public.admin_notifications enable row level security;
alter table public.admin_notification_receipts enable row level security;
revoke all on public.admin_notifications,public.admin_notification_receipts from public,anon,authenticated;
grant select on public.admin_notifications to service_role;
grant select,insert,update on public.admin_notification_receipts to service_role;

create or replace function app_private.capture_admin_order_notification()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_kind text; v_title text; v_model text; v_client text;
begin
  if tg_op = 'INSERT' then
    v_kind := 'new_order'; v_title := 'Nova OS #' || new.id_os;
  elsif old.status is distinct from new.status then
    case new.status
      when 'aguardando peça' then v_kind := 'waiting_part'; v_title := 'OS #' || new.id_os || ' aguardando peça';
      when 'pronto' then v_kind := 'ready'; v_title := 'OS #' || new.id_os || ' pronta para entrega';
      when 'cancelada' then v_kind := 'cancelled'; v_title := 'OS #' || new.id_os || ' cancelada';
      else return new;
    end case;
  else return new;
  end if;
  select m.modelo,c.nome into v_model,v_client from public.moto m
    join public.cliente c on c.id_cliente=m.id_cliente where m.id_moto=new.id_moto;
  insert into public.admin_notifications(kind,order_id,title,body)
    values(v_kind,new.id_os,v_title,concat_ws(' · ',v_client,v_model));
  return new;
end $$;
revoke all on function app_private.capture_admin_order_notification() from public,anon,authenticated;
create trigger notify_admin_order
  after insert or update of status on public.ordem_servico
  for each row execute function app_private.capture_admin_order_notification();
